version: '3.8'
services:
  app:
    build:
      context: .
    volumes:
      - .:/${PWD}
    command: sh -c "while sleep 1000; do :; done"
  mongodb:
    image: mongo:6.0
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
